### PR TITLE
fix(style): extra dots for trailing spaces showing

### PR DESCRIPTION
**Pull request by craftzdog**
movie

It fixes above bug.

### CODE REVIEW

**Comment by coderaiser** [comment]
I can't reproduce this, just added 3 trailing spaces, using [dword](https://github.com/cloudcmd/dword)
Screenshot from 2019-12-16 11-32-02

What font do you use?

**Comment by craftzdog** [comment]
I'm using CodeMirror@5.48.0 with "SauceCodePro Nerd Font" but I even get the same result with Helvetica.
That's interesting. Do you get DOMs like this?

Screen Shot 2019-12-16 at 19 38 48

There are `<span class="cm-trailing-space-a|b vm-whitespace cm-whitespace-*">` for each trailing space character. That is causing the issue.
I found that it happens only on gfm syntax and I have a customized one.
Maybe it's my code's fault.

**Comment by coderaiser** [comment]
I have such styles
Screenshot from 2019-12-16 12-52-18

**Comment by craftzdog** [comment]
You can reproduce it on GFM mode here: https://codemirror.net/mode/gfm/

**Comment by coderaiser** [comment]
Thank you :), fixed with https://github.com/coderaiser/cm-show-invisibles/commit/86a1f631912a112dd888dbe41cf0accbb3943229, landed in [v3.0.0](https://github.com/coderaiser/cm-show-invisibles/releases/tag/v3.0.0) :tada:

**Comment by craftzdog** [comment]
Thank you for the fix!
BTW, it looks like the "main" field in "package.json" is incorrect. It should be `lib/show-invisibles.js`. Could you fix it? https://github.com/coderaiser/cm-show-invisibles/blob/master/package.json#L5

**Comment by coderaiser** [comment]
@craftzdog landed in [v3.0.1](https://github.com/coderaiser/cm-show-invisibles/releases/tag/v3.0.1) :tada:

**Pull request closed without merging**
